name: Test changelog

on:
  workflow_dispatch:
    inputs:
      # TODO: Move to secrets
      token:
        description: 'Github api token'
        required: true
      version:
        description: 'Release version'
        required: true

env:
  GITHUB_TOKEN: ${{ github.event.inputs.token }}
  NEW_VERSION: ${{ github.event.inputs.version }}

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: 1.0.0
          toTag: HEAD
          failOnError: true
          configuration: .github/changelogconfig/configuration.json
          owner: vivid-money
          repo: elmslie

      - name: Print Changelog from output
        run: |
          if [ ${{ steps.github_release.outputs.failed }} = true]; then
            echo "::error ::Failed to generate changelog"
            exit 1
          fi
          cat << EOF
          ${{ steps.github_release.outputs.changelog }}
          EOF