name: Test changelog

on:
  workflow_dispatch:
    inputs:
      # TODO: Move to secrets
      token:
        description: 'Github api token'
        required: true

env:
  GITHUB_TOKEN: ${{ github.event.inputs.token }}

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          outputFile: CHANGELOG-tmp
          fromTag: 1.0.8
          toTag: 1.1.0
          failOnError: true
          configuration: .github/changelogconfig/configuration.json

      - name: Print Changelog from output
        run: |
          if [ ${{ steps.github_release.outputs.failed }} = true]; then
            echo "::error ::Failed to generate changelog"
            exit 1
          fi
          echo ${{ steps.github_release.outputs.changelog }}

      - name: Print changelog from file
        run: cat CHANGELOG-tmp