name: Publish library release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Library release version'
        required: true
      plugin_version:
        description: 'Plugin release version'
        required: false
        default: "none"

env:
  NEW_VERSION: ${{ github.event.inputs.version }}
  NEW_PLUGIN_VERSION: ${{ github.event.inputs.plugin_version }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main branch
        run: ./.github/sh/validate_main_branch.sh

      - name: Validate library version update
        run: ./.github/sh/validate_version_update.sh "libraryVersion" "$NEW_VERSION"

      - name: Validate plugin version update
        if: github.event.inputs.plugin_version != 'none'
        run: ./.github/sh/validate_version_update.sh "pluginVersion" "$NEW_PLUGIN_VERSION"

      - name: Validate jitpack publishing
        run: |
          ./gradlew \
              -Pgroup=com.github.vivid-money \
              -Pversion=$VERSION \
              -xtest \
              -xlint \
              build \
              publishToMavenLocal

  release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update library version
        run: ./.github/sh/update_release_version "libraryVersion" "$NEW_VERSION"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update library version to ${{ env.NEW_VERSION }}"
          file_pattern: gradle.properties
          skip_dirty_check: true

      - name: Update plugin version
        if: github.event.inputs.plugin_version != 'none'
        run: ./.github/sh/update_release_version "pluginVersion" "$NEW_PLUGIN_VERSION"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.plugin_version != 'none'
        with:
          commit_message: "Update plugin version to ${{ env.NEW_PLUGIN_VERSION }}"
          file_pattern: gradle.properties
          skip_dirty_check: true

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          toTag: HEAD
          failOnError: true
          configuration: .github/changelogconfig/configuration.json
          owner: diklimchuk
          repo: elmslie
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ env.NEW_VERSION }}"
          body: ${{ steps.github_release.outputs.changelog }}
          artifacts: "elmslie-plugin/build/distributions/*.zip"
